<?php
/**
 * WebHop Custom Theme — functions.php
 * Generated by WebHop AI Website Builder
 * https://webhop.ai | PLEX Automation
 */

defined('ABSPATH') || exit;

define('WEBHOP_VERSION', '1.0.0');
define('WEBHOP_DIR', get_template_directory());
define('WEBHOP_URI', get_template_directory_uri());

// ── Theme Setup ───────────────────────────────────────────────────────────────
function webhop_setup() {
    // Translations
    load_theme_textdomain('webhop-theme', WEBHOP_DIR . '/languages');

    // Theme supports
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('html5', [
        'comment-list', 'comment-form', 'search-form',
        'gallery', 'caption', 'style', 'script'
    ]);
    add_theme_support('customize-selective-refresh-widgets');
    add_theme_support('wp-block-styles');
    add_theme_support('align-wide');
    add_theme_support('editor-styles');
    add_theme_support('responsive-embeds');
    add_theme_support('custom-logo', [
        'height'      => 60,
        'width'       => 240,
        'flex-height' => true,
        'flex-width'  => true,
    ]);

    // Custom header
    add_theme_support('custom-header', [
        'default-image' => '',
        'width'         => 1920,
        'height'        => 600,
        'flex-height'   => true,
    ]);

    // Nav menus
    register_nav_menus([
        'primary' => __('Primary Navigation', 'webhop-theme'),
        'footer'  => __('Footer Navigation', 'webhop-theme'),
    ]);

    // Image sizes
    add_image_size('webhop-hero',      1920, 900, true);
    add_image_size('webhop-feature',   800,  600, true);
    add_image_size('webhop-card',      600,  450, true);
    add_image_size('webhop-thumb',     400,  300, true);
}
add_action('after_setup_theme', 'webhop_setup');

// ── Enqueue Assets ────────────────────────────────────────────────────────────
function webhop_enqueue_assets() {
    // Get brand colors from options
    $primary   = get_option('webhop_primary_color', '#1A1A1A');
    $secondary = get_option('webhop_secondary_color', '#2A2A2A');
    $accent    = get_option('webhop_accent_color', '#C8E20A');
    $font_h    = get_option('webhop_font_primary', 'Inter');
    $font_b    = get_option('webhop_font_secondary', 'Inter');

    // Google Fonts
    $fonts_url = '';
    $font_families = array_unique([$font_h, $font_b]);
    $font_query = implode('&family=', array_map(
        fn($f) => urlencode($f) . ':wght@400;500;600;700',
        $font_families
    ));
    if ($font_query) {
        $fonts_url = 'https://fonts.googleapis.com/css2?family=' . $font_query . '&display=swap';
        wp_enqueue_style('webhop-google-fonts', $fonts_url, [], null);
    }

    // Main stylesheet
    wp_enqueue_style(
        'webhop-style',
        get_stylesheet_uri(),
        ['webhop-google-fonts'],
        WEBHOP_VERSION
    );

    // Inject CSS custom properties
    $custom_props = "
    :root {
        --webhop-primary:    {$primary};
        --webhop-secondary:  {$secondary};
        --webhop-accent:     {$accent};
        --webhop-font-primary:   '{$font_h}', sans-serif;
        --webhop-font-secondary: '{$font_b}', sans-serif;
    }";
    wp_add_inline_style('webhop-style', $custom_props);

    // Main JS
    wp_enqueue_script(
        'webhop-main',
        WEBHOP_URI . '/assets/js/main.js',
        [],
        WEBHOP_VERSION,
        true
    );

    // Comment reply script
    if (is_singular() && comments_open() && get_option('thread_comments')) {
        wp_enqueue_script('comment-reply');
    }

    // Localize for JS
    wp_localize_script('webhop-main', 'webhop', [
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'nonce'   => wp_create_nonce('webhop-nonce'),
        'siteUrl' => get_site_url(),
    ]);
}
add_action('wp_enqueue_scripts', 'webhop_enqueue_assets');

// ── Widgets ───────────────────────────────────────────────────────────────────
function webhop_register_sidebars() {
    register_sidebar([
        'name'          => __('Footer Widget Area', 'webhop-theme'),
        'id'            => 'footer-widgets',
        'before_widget' => '<div class="footer-widget">',
        'after_widget'  => '</div>',
        'before_title'  => '<h4 class="widget-title">',
        'after_title'   => '</h4>',
    ]);
}
add_action('widgets_init', 'webhop_register_sidebars');

// ── REST API Enhancements ─────────────────────────────────────────────────────
function webhop_rest_cors() {
    $allowed_origins = [
        get_option('webhop_builder_url', 'http://localhost:4000'),
        get_option('siteurl'),
    ];

    $origin = $_SERVER['HTTP_ORIGIN'] ?? '';
    if (in_array($origin, $allowed_origins)) {
        header("Access-Control-Allow-Origin: {$origin}");
        header('Access-Control-Allow-Credentials: true');
        header('Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS');
        header('Access-Control-Allow-Headers: Authorization, Content-Type, X-WP-Nonce');
    }
}
add_action('rest_api_init', 'webhop_rest_cors', 15);

// ── WebHop Brand Options ──────────────────────────────────────────────────────
function webhop_register_settings() {
    $options = [
        'webhop_primary_color',
        'webhop_secondary_color',
        'webhop_accent_color',
        'webhop_font_primary',
        'webhop_font_secondary',
        'webhop_builder_url',
        'webhop_business_name',
        'webhop_tagline',
        'webhop_phone',
        'webhop_email',
        'webhop_address',
    ];

    foreach ($options as $option) {
        register_setting('webhop_options', $option, [
            'show_in_rest' => true,
        ]);
    }
}
add_action('init', 'webhop_register_settings');

// ── Custom REST endpoint for theme config ─────────────────────────────────────
add_action('rest_api_init', function () {
    register_rest_route('webhop/v1', '/brand', [
        'methods'             => 'POST',
        'callback'            => 'webhop_update_brand',
        'permission_callback' => function () {
            return current_user_can('manage_options');
        },
    ]);

    register_rest_route('webhop/v1', '/brand', [
        'methods'             => 'GET',
        'callback'            => 'webhop_get_brand',
        'permission_callback' => '__return_true',
    ]);
});

function webhop_update_brand(WP_REST_Request $request): WP_REST_Response {
    $params = $request->get_json_params();
    $fields = [
        'primaryColor'    => 'webhop_primary_color',
        'secondaryColor'  => 'webhop_secondary_color',
        'accentColor'     => 'webhop_accent_color',
        'fontPrimary'     => 'webhop_font_primary',
        'fontSecondary'   => 'webhop_font_secondary',
        'businessName'    => 'webhop_business_name',
        'tagline'         => 'webhop_tagline',
        'phone'           => 'webhop_phone',
        'email'           => 'webhop_email',
        'address'         => 'webhop_address',
    ];

    foreach ($fields as $param => $option) {
        if (isset($params[$param])) {
            update_option($option, sanitize_text_field($params[$param]));
        }
    }

    return new WP_REST_Response(['success' => true], 200);
}

function webhop_get_brand(): WP_REST_Response {
    return new WP_REST_Response([
        'primaryColor'   => get_option('webhop_primary_color', '#1A1A1A'),
        'secondaryColor' => get_option('webhop_secondary_color', '#2A2A2A'),
        'accentColor'    => get_option('webhop_accent_color', '#C8E20A'),
        'fontPrimary'    => get_option('webhop_font_primary', 'Inter'),
        'fontSecondary'  => get_option('webhop_font_secondary', 'Inter'),
        'businessName'   => get_option('webhop_business_name', get_bloginfo('name')),
        'tagline'        => get_option('webhop_tagline', get_bloginfo('description')),
    ], 200);
}

// ── Custom CSS injection endpoint ─────────────────────────────────────────────
add_action('rest_api_init', function () {
    register_rest_route('webhop/v1', '/custom-css', [
        'methods'             => 'POST',
        'callback'            => function (WP_REST_Request $req) {
            $css = $req->get_param('css');
            if ($css) {
                wp_update_custom_css_post($css);
                return new WP_REST_Response(['success' => true]);
            }
            return new WP_REST_Response(['error' => 'No CSS provided'], 400);
        },
        'permission_callback' => function () {
            return current_user_can('edit_theme_options');
        },
    ]);
});

// ── Disable unnecessary WordPress defaults for performance ─────────────────────
remove_action('wp_head', 'wp_generator');
remove_action('wp_head', 'rsd_link');
remove_action('wp_head', 'wlwmanifest_link');
remove_action('wp_head', 'wp_shortlink_wp_head');
remove_action('wp_head', 'print_emoji_detection_script', 7);
remove_action('wp_print_styles', 'print_emoji_styles');
remove_action('admin_print_scripts', 'print_emoji_detection_script');
remove_action('admin_print_styles', 'print_emoji_styles');

// Disable XML-RPC
add_filter('xmlrpc_enabled', '__return_false');

// Cleanup head
add_filter('the_generator', '__return_empty_string');

// ── Custom excerpt length ─────────────────────────────────────────────────────
add_filter('excerpt_length', fn() => 25, 999);
add_filter('excerpt_more', fn() => '…');

// ── Responsive images ─────────────────────────────────────────────────────────
add_filter('wp_lazy_loading_enabled', '__return_true');
